# Generated by Django 6.0.4 on 2026-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_meallog"),
    ]

    operations = [
        migrations.AddField(
            model_name="meallog",
            name="calories",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meallog",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="meallog",
            name="fats",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="meallog",
            name="protein",
            field=models.FloatField(default=0),
        ),
    ]
