# Generated by Django 6.0.4 on 2026-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_meallog_calories_meallog_description_meallog_fats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("doctor", "Doctor/Nutritionist")],
                default="patient",
                max_length=10,
            ),
        ),
    ]
