# Generated by Django 6.0.4 on 2026-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_meallog_doctor_feedback_meallog_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meallog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="meal_selfies/"),
        ),
    ]
